<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<nav class="navbar navbar-expand-lg navbar-light bg-light p-5">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="order">Checkout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/setting">Setting</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">checkout</a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="addpro">Add Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="role">Add Role</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="role/action">Action</a>
      </li>
    </ul>
   </div>
</nav>
<div class="card mb-3">
  <?php
  // foreach($book as $key){
    ?>
  <img class="card-img-top" style="height: 328px;width: 283px;" src="https://covers.openlibrary.org/b/ISBN/<?php echo $val;?>-S.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><?php echo $book->details->title ; ?></h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
  <?php  ?>
</div>
</section>
<!-- partial -->
  
</body>
</html>
